appId: ${APP_ID}
---
# Sequential Execution Order
executionOrder:
  continueOnFailure: false
  flowsOrder:
    - auth/signup_validation
    - auth/sign_up
    - auth/login_validation
    - auth/login
    - navigation/tabs
