

### 

# @name Sign In

POST {{NEXT_PUBLIC_API_URL}}/auth/sign-in HTTP/1.1
Content-Type: application/json

{
  "email": "1f6w0e@example.com",
    "password": "password2C@"
}

### 

# @name Sign up

POST {{NEXT_PUBLIC_API_URL}}/auth/sign-up HTTP/1.1
Content-Type: application/json

{
  "first_name":"Harrison",
    "last_name":"jurwa",
    "email": "1f6w0e@example.com",
    "password": "password2C@"
}

### 

# @name refresh token 

POST {{NEXT_PUBLIC_API_URL}}/auth/refresh HTTP/1.1
Content-Type: application/json

{
    "refresh_token": "{{REFRESH_TOKEN}}"
}

### 

# @name get me

GET {{NEXT_PUBLIC_API_URL}}/auth/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}


### 

# @name get me

POST {{NEXT_PUBLIC_API_URL}}/auth/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{REFRESH_TOKEN}}
