

### 

# @name Sign In

POST {{NEXT_PUBLIC_API_URL}}/auth/sign-in HTTP/1.1
Content-Type: application/json

{
  "email": "1f6w0e@example.com",
    "password": "password2C@"
}

### 

# @name Sign up

POST {{NEXT_PUBLIC_API_URL}}/auth/sign-up HTTP/1.1
Content-Type: application/json

{
  "first_name":"Harrison",
    "last_name":"jurwa",
    "email": "one@gmail.com",
    "password": "123Clashofclan@",
    "confirm_password": "123Clashofclan@"
}

### 

# @name refresh token 

POST {{NEXT_PUBLIC_API_URL}}/auth/refresh HTTP/1.1
Content-Type: application/json

{
   "refresh_token": "{{REFRESH_TOKEN}}"
}

### 

# @name get me

GET {{NEXT_PUBLIC_API_URL}}/auth/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}


### 

# @name logout 

POST {{NEXT_PUBLIC_API_URL}}/auth/logout HTTP/1.1
Content-Type: application/json

{
  "refresh_token": {{REFRESH_TOKEN}}
}

### 

# @name employees

GET {{NEXT_PUBLIC_API_URL}}/employees HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

### 

# @name unique employees

GET {{NEXT_PUBLIC_API_URL}}/employees/ee535703-2dc5-4c2d-872b-67987a10139a
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

### 

# @name  employees salary slip

GET {{NEXT_PUBLIC_API_URL}}/employees/ee535703-2dc5-4c2d-872b-67987a10139a/salary
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

### 

# @name  Test 

GET http://localhost:3000/api/auth/123/abc
Content-Type: application/json
