@employeeId=940360c8-000b-46cc-b400-f3f49a8e7294

### 

# @name Sign In

POST {{NEXT_PUBLIC_API_URL}}/auth/sign-in HTTP/1.1
Content-Type: application/json

{
  "email": "one@gmail.com",
    "password": "123Clashofclan@"
}

### 

# @name Sign up

POST {{NEXT_PUBLIC_API_URL}}/auth/sign-up HTTP/1.1
Content-Type: application/json

{
  "first_name":"Harrison",
    "last_name":"jurwa",
    "email": "one@gmail.com",
    "password": "123Clashofclan@",
    "confirm_password": "123Clashofclan@"
}

### 

# @name refresh token 

POST {{NEXT_PUBLIC_API_URL}}/auth/refresh HTTP/1.1
Content-Type: application/json

{
   "refresh_token": "{{REFRESH_TOKEN}}"
}

### 

# @name get me

GET {{NEXT_PUBLIC_API_URL}}/auth/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}


### 

# @name logout 

POST {{NEXT_PUBLIC_API_URL}}/auth/logout HTTP/1.1
Content-Type: application/json

{
  "refresh_token": {{REFRESH_TOKEN}}
}

### 

# @name employees

GET {{NEXT_PUBLIC_API_URL}}/employees HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

### 

# @name unique employees

GET {{NEXT_PUBLIC_API_URL}}/employees/ee535703-2dc5-4c2d-872b-67987a10139a
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

### 

# @name  employees salary slip

GET {{NEXT_PUBLIC_API_URL}}/employees/ee535703-2dc5-4c2d-872b-67987a10139a/salary
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

### 

# @name  pension

GET http://localhost:3000/api/employees/{{employeeId}}/pension
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

### 

# @name  pension

GET http://localhost:3000/api/employees/{{employeeId}}/leave
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

### 

# @name register push token

POST http://localhost:3000/api/notification/register
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
      "token": "ExponentPushToken[o-FbhOHTwI4wCykP9axgir]",
      "user_id": "f8119f49-179f-43b9-b9e3-a2ff2b4ba642"
   }
