@token="WEo4U3NiNXFiNWJlZl9KemdhNU1nV1NzUnJBYTp3eHd4NzJDd0lnc0J2aXhkOFlCWUloVGJocDhh"

###
# @name getMe
POST https://10.179.35.48:9443/oauth2/token

{
   "grant_type" : "client_credentials"
}

###
# @name getMe
POST https://10.179.35.48:8243/eisdatafetcher_uat/1.0/make_request
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{ 

}
